@startuml Outline

actor Client

frame Nyandis {
    usecase Server
    queue InstructionQueue
    node Cores
    collections Trie

    queue BroadCaster
}

frame AnotherNyandis

Client -left-> Server: send Request
Server -down-> InstructionQueue: enqueue instruction
Cores -right-> InstructionQueue: pull instruction
Cores -left-> Trie: operate instruction
Trie -right-> Cores: return result
Cores -up-> Server: return result
Cores -up-> BroadCaster: push result
Server -right-> Client: return result
BroadCaster -up-> AnotherNyandis: broadcast result over H2

@enduml